apiVersion: v2
name: linkvault
description: A bookmark manager with tagging, collections, and public sharing
type: application
version: 2.7.0
appVersion: "2.7.0"

dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: "20.6.1"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: replicated
    version: "1.x.x"
    repository: oci://registry.replicated.com/library
