replicaCount: 1

image:
  repository: proxy.link-vaults.com/proxy/linkvault-lynx/bennyyang11/linkvault
  tag: "3.0.0"
  pullPolicy: IfNotPresent

initImage:
  repository: proxy.link-vaults.com/proxy/linkvault-lynx/library/busybox
  tag: "1.36"

replicated:
  nameOverride: "linkvault-sdk"


service:
  type: NodePort
  port: 8080
  nodePort: 30080

ingress:
  enabled: false
  host: ""
  className: nginx
  annotations: {}
  tls:
    enabled: false
    certManager:
      enabled: false
      issuerName: "letsencrypt-prod"
      issuerKind: "ClusterIssuer"
    secretName: ""
    selfSigned: false

config:
  pollIntervalSeconds: "10"
  reportIntervalSeconds: "60"
  updateCheckIntervalSeconds: "300"

# --- Embedded PostgreSQL (Bitnami subchart) ---
postgresql:
  enabled: true
  image:
    registry: public.ecr.aws
    repository: bitnami/postgresql
  auth:
    postgresPassword: "linkvault-default-pw"
    database: "linkvault"
  primary:
    persistence:
      size: 1Gi

# BYO PostgreSQL
externalPostgresql:
  host: ""
  port: "5432"
  user: "postgres"
  password: ""
  database: "linkvault"
  existingSecret: ""

# --- Embedded Redis (Bitnami subchart) ---
redis:
  enabled: true
  architecture: standalone
  image:
    registry: public.ecr.aws
    repository: bitnami/redis
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

# BYO Redis
externalRedis:
  host: ""
  port: "6379"
  password: ""
  existingSecret: ""

# --- Global settings ---
global:
  security:
    allowInsecureImages: true
  imagePullSecrets:
    - name: enterprise-pull-secret
  replicated:
    licenseID: ""
