apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: "3.0.0-alpha-31+k8s-1.34"
  domains:
    proxyRegistryDomain: proxy.link-vaults.com
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          workerProfiles:
          - name: custom-settings
            values:
              maxPods: 110
              maxParallelImagePulls: 5
