apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: linkvault
spec:
  chart:
    name: linkvault
    chartVersion: 3.0.0
  releaseName: linkvault
  namespace: default
  values:
    image:
      repository: bennyyang11/linkvault
    initImage:
      repository: busybox
    ingress:
      enabled: false
    service:
      nodePort: 30880
    postgresql:
      enabled: '{{repl ConfigOptionEquals "db_type" "embedded"}}'
    externalPostgresql:
      host: '{{repl ConfigOption "external_db_host"}}'
      port: '{{repl ConfigOption "external_db_port"}}'
      user: '{{repl ConfigOption "external_db_user"}}'
      password: '{{repl ConfigOption "external_db_password"}}'
      database: '{{repl ConfigOption "external_db_name"}}'
    redis:
      enabled: '{{repl ConfigOptionEquals "cache_type" "embedded"}}'
    externalRedis:
      host: '{{repl ConfigOption "external_redis_host"}}'
      port: '{{repl ConfigOption "external_redis_port"}}'
      password: '{{repl ConfigOption "external_redis_password"}}'
  optionalValues:
    - when: '{{repl ConfigOptionEquals "db_type" "embedded"}}'
      recursiveMerge: false
      values:
        postgresql:
          auth:
            postgresPassword: '{{repl ConfigOption "embedded_db_password"}}'
  builder: {}
