apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: linkvault
spec:
  chart:
    name: linkvault
    chartVersion: 3.1.0
  releaseName: linkvault
  namespace: default
  values:
    image:
      repository: proxy.link-vaults.com/proxy/linkvault-lynx/docker.io/bennyyang11/linkvault
    initImage:
      repository: proxy.link-vaults.com/proxy/linkvault-lynx/docker.io/library/busybox
    ingress:
      enabled: false
    service:
      nodePort: 30880
    postgresql:
      enabled: '{{repl ConfigOptionEquals "db_type" "embedded"}}'
    externalPostgresql:
      host: '{{repl ConfigOption "external_db_host"}}'
      port: '{{repl ConfigOption "external_db_port"}}'
      user: '{{repl ConfigOption "external_db_user"}}'
      password: '{{repl ConfigOption "external_db_password"}}'
      database: '{{repl ConfigOption "external_db_name"}}'
    redis:
      enabled: '{{repl ConfigOptionEquals "cache_type" "embedded"}}'
    externalRedis:
      host: '{{repl ConfigOption "external_redis_host"}}'
      port: '{{repl ConfigOption "external_redis_port"}}'
      password: '{{repl ConfigOption "external_redis_password"}}'
  optionalValues:
    - when: '{{repl ConfigOptionEquals "db_type" "embedded"}}'
      recursiveMerge: true
      values:
        postgresql:
          auth:
            postgresPassword: '{{repl ConfigOption "embedded_db_password"}}'
    - when: '{{repl HasLocalRegistry}}'
      recursiveMerge: true
      values:
        image:
          repository: '{{repl LocalRegistryHost}}/{{repl LocalRegistryNamespace}}/linkvault'
        initImage:
          repository: '{{repl LocalRegistryHost}}/{{repl LocalRegistryNamespace}}/busybox'
        postgresql:
          image:
            registry: '{{repl LocalRegistryHost}}'
            repository: '{{repl LocalRegistryNamespace}}/postgresql'
        redis:
          image:
            registry: '{{repl LocalRegistryHost}}'
            repository: '{{repl LocalRegistryNamespace}}/redis'
        replicated:
          image:
            registry: '{{repl LocalRegistryHost}}'
            repository: '{{repl LocalRegistryNamespace}}/replicated-sdk-image'
  builder:
    postgresql:
      enabled: true
    redis:
      enabled: true
