{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "linkvault.fullname" . }}
  labels:
    {{- include "linkvault.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- if .Values.ingress.tls.certManager.enabled }}
    cert-manager.io/{{ .Values.ingress.tls.certManager.issuerKind | lower }}: {{ .Values.ingress.tls.certManager.issuerName | quote }}
    {{- end }}
    {{- if .Values.ingress.tls.selfSigned }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- else if .Values.ingress.tls.certManager.enabled }}
      secretName: {{ include "linkvault.fullname" . }}-tls
      {{- else if .Values.ingress.tls.selfSigned }}
      secretName: {{ include "linkvault.fullname" . }}-tls-self-signed
      {{- end }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "linkvault.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
